version: '3.8'

services:
  db:
    image: postgres:17
    container_name: n8n-db
    hostname: n8n-db
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "n8n", "-U", "n8ndbuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      TZ: America/New_York  # adjust to your timezone
      POSTGRES_DB: n8n
      POSTGRES_USER: n8ndbuser
      POSTGRES_PASSWORD: n8ndbpass  # CHANGE THIS to a strong password
    volumes:
      - /volume1/docker/n8n/db:/var/lib/postgresql/data:rw
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    restart: on-failure:5
    user: 0:0
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5678:5678
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5678 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      N8N_HOST: n8n.yourname.synology.me  # CHANGE THIS to your domain
      WEBHOOK_URL: https://n8n.yourname.synology.me  # CHANGE THIS to your domain
      GENERIC_TIMEZONE: America/New_York  # adjust to your timezone
      TZ: America/New_York
      N8N_PORT: 5678
      N8N_ENCRYPTION_KEY: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr  # GENERATE A NEW KEY openssl rand -hex 32!
      N8N_PROTOCOL: https
      NODE_ENV: production
      N8N_RUNNERS_ENABLED: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_SECURE_COOKIE: true  # Set to false if not using synology.me DDNS
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8ndbuser
      DB_POSTGRESDB_PASSWORD: n8ndbpass  # CHANGE THIS to match db password
    volumes:
      - /volume1/docker/n8n/data:/root/.n8n:rw
      - /volume1/docker/n8n/files:/files:rw
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
